# Generated by Django 3.2.7 on 2021-10-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_platformuser_enable_automatic_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformuser',
            name='unimore_password',
            field=models.CharField(max_length=500),
        ),
    ]
