# Generated by Django 3.2.7 on 2021-10-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_platformuser_unimore_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformuser',
            name='enable_automatic_reservation',
            field=models.BooleanField(default=True),
        ),
    ]
