# Generated by Django 3.2.7 on 2021-10-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_platformuser_privacy_and_cookie_policy_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='green_pass_link',
            field=models.URLField(default=None, null=True),
        ),
    ]
