# Generated by Django 3.2.7 on 2021-10-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_platformuser_green_pass_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformuser',
            name='green_pass_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
