# Generated by Django 3.2.7 on 2021-10-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_auto_20211023_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='feedback',
            field=models.BooleanField(default=True),
        ),
    ]
