# Generated by Django 3.2.7 on 2021-11-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0014_platformuser_whats_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='ask_feedback',
            field=models.BooleanField(default=True),
        ),
    ]
