# Generated by Django 3.2.7 on 2021-10-17 12:52

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0007_alter_lesson_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(check=models.Q(('start_time__lt', django.db.models.expressions.F('end_time'))), name='start_before_end'),
        ),
    ]
