# Generated by Django 3.2.7 on 2021-10-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0015_alter_classroom_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['building__name', 'name']},
        ),
    ]
