# Generated by Django 3.2.7 on 2021-10-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0016_alter_classroom_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name']},
        ),
    ]
