# Generated by Django 3.2.7 on 2021-10-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0020_greenpass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GreenPass',
        ),
    ]
