# Generated by Django 3.2.7 on 2021-10-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0008_lesson_start_before_end'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lesson',
            name='start_before_end',
        ),
    ]
