# Generated by Django 3.2.7 on 2021-10-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0011_logs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='Log',
        ),
    ]
