# Generated by Django 3.2.7 on 2021-10-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0013_auto_20211017_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['building']},
        ),
    ]
