# Generated by Django 3.2.7 on 2021-10-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0018_auto_20211018_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['start_time', 'end_time']},
        ),
    ]
