# Generated by Django 3.2.7 on 2021-11-20 09:14

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0022_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#FF5964', 'Ninja red'), ('#69DC9E', 'Ninja green'), ('#0075A2', 'Ninja blue'), ('#333333', 'Ninja black'), ('#FF9F1C', 'Ninja orange'), ('#E3DFFF', 'Ninja lilla'), ('#3D3A4B', 'Ninja grey'), ('#849483', 'Ninja olive'), ('#B388EB', 'Ninja purple'), ('#823329', 'Ninja burnt umber')], default='#FF5964', max_length=18),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
