# Generated by Django 3.2.7 on 2021-11-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0024_alter_lesson_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='color',
            field=models.CharField(choices=[('#FF5964', '<h1>Ciao</h1>'), ('#69DC9E', 'Ninja green'), ('#0075A2', 'Ninja blue'), ('#333333', 'Ninja black'), ('#FF9F1C', 'Ninja orange'), ('#E3DFFF', 'Ninja lilla'), ('#3D3A4B', 'Ninja grey'), ('#849483', 'Ninja olive'), ('#B388EB', 'Ninja purple'), ('#823329', 'Ninja burnt umber')], default='#FF5964', max_length=7),
        ),
    ]
