# Generated by Django 3.2.7 on 2021-11-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0024_alter_lesson_name'),
        ('reservation_management', '0024_auto_20211106_0142'),
    ]

    operations = [
    ]
