# Generated by Django 3.2.7 on 2021-10-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_alter_platformuser_enable_automatic_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='privacy_and_cookie_policy_acceptance',
            field=models.BooleanField(default=False),
        ),
    ]
