# Generated by Django 3.2.7 on 2021-10-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_alter_platformuser_green_pass_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='wrong_unimore_credentials',
            field=models.BooleanField(default=False),
        ),
    ]
