# Generated by Django 3.2.7 on 2021-10-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_platformuser_wrong_unimore_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformuser',
            name='wrong_unimore_credentials',
        ),
        migrations.AddField(
            model_name='platformuser',
            name='credentials_ok',
            field=models.BooleanField(default=True),
        ),
    ]
