# Generated by Django 3.2.7 on 2021-11-06 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_management', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
                INSERT INTO analytics_management_log (
                    id,
                    execution_time,
                    users,
                    lessons,
                    date
                )
                SELECT
                    id,
                    execution_time,
                    users,
                    lessons,
                    date
                FROM
                    reservation_management_log;
            """, reverse_sql="""
                INSERT INTO reservation_management_log (
                    id,
                    execution_time,
                    users,
                    lessons,
                    date
                )
                SELECT
                    id,
                    execution_time,
                    users,
                    lessons,
                    date
                FROM
                    analytics_management_log;
            """),
        migrations.RunSQL("""
                INSERT INTO analytics_management_feedback (
                    id,
                    user_id,
                    ok,
                    date
                )
                SELECT
                    id,
                    user_id,
                    ok,
                    date
                FROM
                    reservation_management_feedback;
            """, reverse_sql="""
                INSERT INTO reservation_management_feedback (
                    id,
                    user_id,
                    ok,
                    date
                )
                SELECT
                    id,
                    user_id,
                    ok,
                    date
                FROM
                    analytics_management_feedback;
            """)

    ]
