# Generated by Django 3.2.7 on 2021-11-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_management', '0002_auto_20211106_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsubscribed_users', models.IntegerField(default=0)),
            ],
        ),
    ]
